### ISSUE TITLE
Can't find the app on the play store anymore?

### ISSUE THREAD

**Issue by owengraven** [ccomeaux/boardgamegeek4android#103]
I reinstalled my phone, and I can't find the app in the play store anymore.

Not even by going to previously installed apps, tried googling and clicking the link on the github but that also says item not found.

Do you know this yet? and is there a fix?

**Comment by bilbothebaggins** [comment]
Hi Chris! Luckily I don't need to re-install at the moment, but is the resolution going well? Would be a real shame to loose the app from the store!

**Comment by owengraven** [comment]
Any info on why it isn't back on the store yet? Google giving you a hard time?

**Comment by tupaschoal** [comment]
Hey Chris,
Any info on this? Is it something people can help you with?

**Comment by tupaschoal** [comment]
@ccomeaux any info?

**Comment by Vinne2** [comment]
Maybe the issue is not only the logo but the name (I mean URI) of the app? Because the URI refers to boardgamegeek.com directly.

**Comment by Vinne2** [comment]
Meanwhile – until this issue is solved – the app could perform a start-up check (@github) if there's a newer version and offer to download the APK directly (or at least to open download page).

**Comment by mhellmeier** [comment]
Why is this issue closed? The app is still not available in the Google Play store.

**Comment by Jeff-Mich** [comment]
> Why is this issue closed? The app is still not available in the Google Play store.

see

https://www.boardgamegeek.com/thread/2248843/back-play-store-bgg-rebranding

**Comment by Kaligula0** [comment]
AFAIK Chris cannot put the app back on Play Store with the same name/packagename after the ban.

On XDA Forums, in the Magisk Thread, right after Magisk app was pulled out of the Play Store, the developer topjohnwuon wrote:

> Now I have two choices: (…) re-release a NEW APP on the store (yes, once your app is pulled down, the package name and app name is permanently banned). The other way is to simply just distribute the app through places like XDA and third-party markets (…).

(→ [source](https://forum.xda-developers.com/t/magisk-the-magic-mask-for-android.3473445/post-72508849))

The same happened to me with an extension for Chrome. Once banned I couldn't do anything for it to come back (eve after required fixes). It would be easier to upload a fixed version as a new extension and lose all the existing users and ratings…
