### ISSUE TITLE
Games' PricePaid isn't synced

### ISSUE THREAD

**Issue by dominiquelee** [ccomeaux/boardgamegeek4android#105]
I have some games with a price paid in €, this price won't appear in:
- the game collection page,
- the games list when ordering on PricePaid.

**Comment by ccomeaux** [comment]
Does the game's collection page say it has synced recently? If so, can you try logging out and back in? Thanks!

**Comment by dominiquelee** [comment]
It does.
The correct move was to log out, log in, clear local data and re-sync. I'm not sure that's the simplest fix, but the "clear local data" part was needed.

Thanks!
