### ISSUE TITLE
Unable to edit wishlist status 

### ISSUE THREAD

**Issue by MarkusShepherd** [ccomeaux/boardgamegeek4android#107]
When I click on a game that already is on my wishlist and try to edit the collection entry to change its wishlist priority (say from like to love to have), then confirm to say, it immediately shows the old priority again and doesn't change anything.

**Comment by MarkusShepherd** [comment]
I am on version 6.6.7

**Comment by zoki666** [comment]
I have the same problem. Try to change priority and uncheck and check again the option. Then save your changes.

**Comment by MarkusShepherd** [comment]
Thanks, that works! Nice workaround for the time being... 👍

**Comment by ccomeaux** [comment]
This bug is fixed in the `develop` branch.
