### ISSUE TITLE
Sorting in MyGames fails when a game is rated with 10

### ISSUE THREAD

**Issue by kayteem** [ccomeaux/boardgamegeek4android#108]
**Use Case:**
- Sorting by "Rate DESC" on the "My Games" view

**Expected behavior:**
- The games are sorted by the ratings:
- result: 10, 9, 8, 7, ...

**Actual behavior:**
- The games are sorted by the rating string
- Since the String "10" starts with one, these games appear way down in the list
- result: 9, 8, 7, ..., 10

**Note:**
- Changing the type of the rating field to a double should fix the sorting issue.

**Comment by ccomeaux** [comment]
This has been addressed.
