### ISSUE TITLE
Feature Request: Edit 'Private Information > Location"

### ISSUE THREAD

**Issue by pvince** [ccomeaux/boardgamegeek4android#111]
When you are editing a 'collection' item you can edit the 'Private Info', including information such as Acquisition Date and Acquired From.

At its most basic level, I would love if I could also edit the 'Inventory Date' and 'Inventory Location'.

As my collection has grown I can no longer store all my games on the shelf in my living room and have started storing some of my less played games in boxes in a store room. It would be nice if I could use the app to update the storage location.

I also have lent out a few of my games to friends, and it would be nice if i could set the storage location to who has the game.

In my ideal world, this would be implemented in a similar fashion to the 'Play Location', where it saves previously used locations and lets me pick them or type in a new one.

**Comment by ccomeaux** [comment]
In the most recent (unreleased) version, you can edit the inventory location, but not the date. Unfortunately, it's not not exposed in BGG's API.
