### ISSUE TITLE
README.md is way out of date and has broken links

### ISSUE THREAD

**Issue by bernd-wechner** [ccomeaux/boardgamegeek4android#116]
Title says it all. But it links to Google+ which is long dead, the link to Play Store is dead and so the whole README conveys the image of a dead project. Is it?

**Comment by tupaschoal** [comment]
Not really, if you click on release you'll see @ccomeaux did one 4d ago. With that being said, he's always done this in on his own and the play store link has been broken for a while

**Comment by bernd-wechner** [comment]
How much trouble is it to fix the README.md then?

**Comment by bernd-wechner** [comment]
I admit Release 6.7 looks like number of a very mature release. And yet I see two PRs dated 2018 still sitting there. And no tips on how to try it out either alas. Would be happy to give it a spin.

**Comment by tupaschoal** [comment]
I'd say it is not a lot of trouble, but only Chris actually knows what's going on.

As for the PRs, #99 was pending something on Chris side, which I don't know if was resolved, but #102 seems straight forward to pick up, if you want to, be my guest.

Getting the app up and running wasn't more difficult than downloading Android studio and letting it load and build there

**Comment by ccomeaux** [comment]
As @tupaschoal said, the project isn't dead. It's mainly a one man labor of love. Two reasons it's been less active than normal - my personal and work life have become crazier and Google removed it from the Play store, killing my spirit a little bit. The README was updated on the develop branch, so you should be able to get this installed now.
