### ISSUE TITLE
When sorting by "Current Value" app crashes

### ISSUE THREAD

**Issue by corkysru** [ccomeaux/boardgamegeek4android#118]
When I sort the games by "Current Value" the app crashes. Not sure if this is related to the quatity of games in my collection (5358) but it even crashes when I filter it to only things I own. Granted this is still 3k+ games. When filtering down to just base games (1569) this sort finally works.

**Comment by ccomeaux** [comment]
Fixed in e5d4bde3fe11c5bcbcbb400865f94d23298f40f8
