### ISSUE TITLE
I don't see negative points in scores

### ISSUE THREAD

**Issue by zoki666** [ccomeaux/boardgamegeek4android#125]
Here are 2 scores: 31 and -3. You can see 31 but y can't see -3 (but the score is saved)
![Screenshot_20191028-084404](https://user-images.githubusercontent.com/28391248/67669757-ce0c2080-f972-11e9-8e69-5fec3e2b8c36.jpg)

**Comment by ccomeaux** [comment]
Oh, me too. I'll look into it.

**Comment by zoki666** [comment]
Fixed (v6.7.1)

Thanks!!!
