### ISSUE TITLE
Strange behaviour when using tags in "wishlist comment" or "trade condition" fields.

### ISSUE THREAD

**Issue by rafal-watorski** [ccomeaux/boardgamegeek4android#127]
I'm using a lot of tags in my collection, usually in "Private comment", "Wishlist comment" and "Trade condition" fields. When editing these fields using the application, the text is changed to html tags. After another sync (trough swiping down), the text is back to normal.

Step by step:
1. Enter "[c]test[/c]" in the the mentioned fields.
2. Save the changes.
3. After collection item gets updated, the "Private comment" field remains the same, but other fields now have the text "<span class='code'>test</span>" displayed.
4. Swipe down to resync.
5. "Wishlist comment" and "Trade condition" now have the original text "[c]test[/c]".

**Comment by ccomeaux** [comment]
I found the problem. When you POST text like `[b]bold[/b]` to BGG, it responds with `<b>bold</b>`, which the apps stores. But BGG stores the correct value, so things are fixed the next time it syncs. Easy fix, coming right up!

**Comment by rafal-watorski** [comment]
Works ok now, thank you.
