### ISSUE TITLE
"Wishlist comment" and "Trade condition" fields rendering

### ISSUE THREAD

**Issue by rafal-watorski** [ccomeaux/boardgamegeek4android#128]
I'm using a lot of tags in my collection, usually in "Private comment", "Wishlist comment" and "Trade condition" fields. Would it be possible to display the resulting text instead of displaying the text with tags (ex. "[c]test[/c]")?

**Comment by ccomeaux** [comment]
I didn't realize those fields supported markup. I'll see what I can do.

**Comment by rafal-watorski** [comment]
Much better now, except for the images. Either way, thank you :)

`[ImageID=2599422 micro inline]`

![Screenshot_2020-04-18-18-39-44-603_com boardgamegeek](https://user-images.githubusercontent.com/4478802/79643738-a456e800-81a4-11ea-972f-edc8ed194ae5.jpg)
