### ISSUE TITLE
Bring Back Sort By Geek Rating

### ISSUE THREAD

**Issue by ZUUL42** [ccomeaux/boardgamegeek4android#130]
The Geek _Rating_ is what is used to determine the Geek _Rank_. It's what keeps a game with a 10 average rating _but only two reviews_ from being BGG's # 1 game.
Some might say, just use Geek Rank for sorting.
Well that's fine for base games (well, not really). However, expansions don't get a Geek _Ranking_. But they do still have a Geek _Rating_ using the same altered [Bayesian averaging](https://en.wikipedia.org/wiki/Bayesian_average) algorithm.
There are a few notes on BGG about the [Geek Rating](https://boardgamegeek.com/wiki/page/BoardGameGeek_FAQ#toc13). I believe there are many other notes on BGG, but I'm not finding them at the moment.
Apparently many people don't like or perhaps just don't understand Geek Rating. That's fine. No one is forced to use it. But removing it _does_ remove it for those that would use it.
I much prefer it because it keeps the unknown, seldom rated games from always showing on the top and it keeps both the base and expansions sorted together.

I believe removing a single string will bring it back [`android:visibility="gone"/`](https://github.com/ccomeaux/boardgamegeek4android/compare/develop...ZUUL42:BringBackGeekRating)

**Comment by ccomeaux** [comment]
I'll go ahead and reinstate filtering by Geek Rating while I'm at it.

**Comment by Vinne2** [comment]
I think it may be closed :) Thank you!
