### ISSUE TITLE
Saved players doesn't last long enough.

### ISSUE THREAD

**Issue by corkysru** [ccomeaux/boardgamegeek4android#133]
If you play multiple games in a row quickly enough it saves the people who played the game and auto-populates this into the next logged play. Which is great. But this seems to reset at midnight and doesn't last long enough. I play long games... Would be great if this last at least 6-8 hours before resetting.

**Comment by Vinne2** [comment]
Or — it could last forever, but ask everytime for permission to autofill players, based on previous game.

**Comment by corkysru** [comment]
> Or — it could last forever, but ask everytime for permission to autofill players, based on previous game.

I think a 12-hour time out would be acceptable. I only say that because another pop-up to always have to click accept to sometimes gets annoying if you're not playing really long games

**Comment by ccomeaux** [comment]
This is fixed in 2a96eca668837cc6a794bfdac29a52d3e2f3c2c6 and should be released soon.
