### ISSUE TITLE
Code won't compile 

### ISSUE THREAD

**Issue by jaqjacek** [ccomeaux/boardgamegeek4android#134]
I try to contribute for this project. 
Downloaded code from master, develop and latest tag 6.7.1 commit 4fc19cbad2e6cbec3bf5ab342555df79b9694f9f and there where problems with compilation
1 Issue:  with dependencies: NestedScrollWebView  AndroidStudio just scream that it could't find that aar file. I fixed that download source code of that project and put class insside app folder.

2 Issue: Class BggApplication uses another classc om.boardgamegeek.events.BggEventBusIndex that is missing in source code. Workaround to comment out uses of that code.

Finaly code compiles and run in AVD

Android Studio 3.5.3
Android Gradle Plugin: 3.5.2
Gradle: 5.4.1

This my first approach  to android studio and maybe I'm doing something wrong ?

BTW very cool app!!!!!

**Comment by aglenn** [comment]
Had the same problem with your first issue. Looks like a problem with the build at JitPack: https://jitpack.io/com/github/tobiasrohloff/NestedScrollWebView/v1.0.2/build.log

The second issue could have been a side effect of the first. That's a generated class, so it might not have been generated when the build failed because of NestScrollWebView.

**Comment by jaqjacek** [comment]
Fresh code from develop commit: 326d4ec8 don't shout about BggEventBusIndex
NestedScrollWebView still don't work missing artifact

New problem that's don't stop compilation but throw strange error: 
`> Task :app:compileDebugJavaWithJavac
Gradle may disable incremental compilation as the following annotation processors are not incremental: jetified-eventbus-annotation-processor-3.1.1.jar (org.greenrobot:eventbus-annotation-processor:3.1.1), jetified-icepick-processor-3.2.0.jar (frankiesardo:icepick-processor:3.2.0), jetified-auto-service-1.0-rc2.jar (com.google.auto.service:auto-service:1.0-rc2).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:139)
	at org.aspectj.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:98)
	at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:186)`

**Comment by ccomeaux** [comment]
I don't know whey NestScrollWebView would be giving you problems. What version of Android Studio are you using?

**Comment by beauxq** [comment]
I just downloaded the latest Android Studio today 3.6.3 and I see the same problem:
ERROR: Failed to resolve: com.github.rhlff:NestedScrollWebView:v1.0.2

**Comment by Vinne2** [comment]
> I just downloaded the latest Android Studio today 3.6.3 and I see the same problem:
> ERROR: Failed to resolve: com.github.rhlff:NestedScrollWebView:v1.0.2

I confirm. I have *no idea what I'm doing* so please be kind to my un-knowledge, but I'm just trying to inspect the error…
Am I supposed to see a file named `Gradle__com_github_rhlff_NestedScrollWebView_v1_0_2_aar.xml` (or similar) in `/.idea/libraries`? Because there are files named like other dependencies but there is no file about NestedScrollWebView. BUT – I don't know if 1) it's not there because the Android Studio hasn't found the dependency (and the `…_arr.xml` file is sth like gradle log) or 2) it hasn't found it because there is no such file (and the `…_arr.xml` file is *the dependency* itself)?

**Comment by Vinne2** [comment]
I also see `cannot resolve symbol 'RuntimeException'` in lines 35, 45 and `cannot resolve symbol 'GregorianCalendar'` in line 77.
![Bez tytułu](https://user-images.githubusercontent.com/3950811/79867071-09495280-83de-11ea-9193-52929afc01c8.png)

**Comment by Vinne2** [comment]
Not only we have this issue, see this issue from month ago → https://github.com/tobiasrohloff/NestedScrollWebView/issues/14
They say the workaround is to import the project as a lib. (Can someone explain me what it means and how to do this?)

**Comment by Cowboyjunkie** [comment]
Hi Vinne2!
In Android Studio at the Bottom is a Tab called "Terminal" chose that and enter
git submodule add https://github.com/rhlff/NestedScrollWebView
After a brief Dialog you open the "settings.gradle" in the root dir of the project (lefthand in android studio) There should only be on line in the file. add the following two line:
include ':NestedScrollWebView:lib'
project(':NestedScrollWebView').projectDir = new File('/NestedScrollWebView')
In the folder "app" open the "build.gradle" and add the following line under "dependencies" (you will see similar lines there.
implementation project(':NestedScrollWebView:lib')
In the same file further down is another line about "nestedscrollwebview": remove that line.

Regards,
John

**Comment by Cowboyjunkie** [comment]
Ohh...nearly forgot:
After you do that Android Studio will give you some error about "mixing java versions".
Simply close Android Studio, delete the ".idea" folder and open AS again.

**Comment by Kaligula0** [comment]
@tobiasrohloff solved his issue on NestedScrollWebView → https://github.com/tobiasrohloff/NestedScrollWebView/issues/14#issuecomment-654181996

**Comment by ccomeaux** [comment]
Fixed with a26e7e81c156a24ecbb8afcdb60b4dc199029d06
