### ISSUE TITLE
Zero points is not displayed

### ISSUE THREAD

**Issue by zoki666** [ccomeaux/boardgamegeek4android#138]
![Screenshot_20200419-101445](https://user-images.githubusercontent.com/28391248/79682945-cdb85800-8226-11ea-806d-4a7cc6600365.jpg)

If I edit it, I can see that there is saved a zero, but it is not displayed.

**Comment by Vinne2** [comment]
I confirm the issue. Looks the same in mine.

**Comment by ccomeaux** [comment]
Yep, me too. I've found and fixed the issue. It will be in the next release candidate. Thanks for checking that!

**Comment by ccomeaux** [comment]
Fixed in [RC2](https://github.com/ccomeaux/boardgamegeek4android/releases/tag/6.8-RC2).

**Comment by Vinne2** [comment]
I see a 0 👍  
![Screenshot_20200420-011759](https://user-images.githubusercontent.com/3950811/79702387-e6ffe980-82a4-11ea-9000-14d0138999e1.png)

**Comment by zoki666** [comment]
Thx!
