### ISSUE TITLE
Some library licenses display "Copyright © YEAR, OWNER"

### ISSUE THREAD

**Issue by Kaligula0** [ccomeaux/boardgamegeek4android#142]
Settings > About > Open source licenses
When you click on a license name under each library you can read the license. Some of the libraries are under Apache Version 2.0 license. And some of these open a license starting e.g. "Copyright © 2018, Mike Penz (...)" and some start with "Copyright © YEAR, OWNER". Among these are:
Anko, Hugo, Icepick, MaterialRangeBar, NestedScrollWebView, etc.

This is an issue in this app or in their repositories?

**Comment by ccomeaux** [comment]
Fixed (as much as I can control) in f815b6ccc023561dce87bb352b240dad577997c0
