### ISSUE TITLE
markdown in Play Comments field 

### ISSUE THREAD

**Issue by Kaligula0** [ccomeaux/boardgamegeek4android#146]
Is it possible to add markdown support in Comments field of a Play? 
![Screenshot_20200502-202025](https://user-images.githubusercontent.com/3950811/80876895-79e44f00-8cbb-11ea-8815-1773d246b590.png)

**Comment by ccomeaux** [comment]
Fixed in 702245377a2b158119ccee97133bd2e44f659048

**Comment by Kaligula0** [comment]
You put it in CHANGELOG.MD to 6.8.0. Was that intentional? I see 6.8.0 is from 20 Apr 2020 while the commit is from 27 May 2020.
