### ISSUE TITLE
The app don't work in LATAM

### ISSUE THREAD

**Issue by jeanpierre994** [ccomeaux/boardgamegeek4android#153]
the application is not available in the latam app store, I'm in Colombia
![Screenshot_20200922-070255_Google Play Store](https://user-images.githubusercontent.com/71705389/93879820-0fe83880-fca2-11ea-8893-6f70ae971223.jpg)

**Comment by ccomeaux** [comment]
The app is no longer available in any store. You will need to side-load it from https://github.com/ccomeaux/boardgamegeek4android/releases.
