### ISSUE TITLE
Login stopped working

### ISSUE THREAD

**Issue by rafal-watorski** [ccomeaux/boardgamegeek4android#166]
BGG changed the login POST a little bit, so it stopped working in the app. It seems that only a small change is needed in the [NetworkAuthenticator.java](/ccomeaux/boardgamegeek4android/blob/develop/app/src/main/java/com/boardgamegeek/auth/NetworkAuthenticator.java) in `buildRequest` function.

- url changed from `"https://www.boardgamegeek.com/login"` to `"https://boardgamegeek.com/login/api/v1"`
- contentType changed from `application/x-www-form-urlencoded` to `application/json`
- payload is not longer a FormBody, but a JSON with following structure:
```
{
    "credentials": {
        "username": "XXXXXXXX",
        "password": "YYYYYYYY"
    }
}
```

**Comment by tvedeane** [comment]
Hey,

Do you have more details regarding this requirement? Ideally link to BGG site mentioning how to login.

My quick hacking to try what you suggested didn't help. Here is code I tried:
```java
@NonNull
private static Request buildRequest(@NonNull String username, @NonNull String password) {
  String body = String.format("{\"credentials\":{\"username\":\"%s\",\"password\":\"%s\"}}", username, password);
  return new Request.Builder()
	  .url("https://boardgamegeek.com/login/api/v1")
	  .post(RequestBody.create(body.getBytes(StandardCharsets.UTF_8)))
	  .addHeader("Content-Type", "application/json")
	  .build();
}
```

If I understand correctly what's happening, BGG server is responding with status code 202, which I'm not sure how to handle.

**Comment by rafal-watorski** [comment]
There are no details on BGG about it. I found it, because my script stopped
working, so I just used browser's dev tools to inspect the current POST
made on login.

I'm not sure why BGG used response code 202 instead of simply 200 in this
case. It's quite confusing, because 202 was usually used when XMLAPI2
requests were accepted for processing and you needed to request the data
later...

Either way, I see that someone has already submitted a pull request :)

Best regards / Pozdrawiam
Rafał


pt., 29 paź 2021 o 20:14 Marek J ***@***.***> napisał(a):

**Comment by tvedeane** [comment]
Fixed in https://github.com/ccomeaux/boardgamegeek4android/pull/167.

**Comment by cmadamsgit** [comment]
Any chance of getting a new release with this fix included? I have a new device and can't log in with this app because of this.

**Comment by tvedeane** [comment]
Good point, we could get a new release (a RC, I guess), but we would need help from @ccomeaux because I never did it before in this repository, so I'm not sure if this should happen from develop branch and how to name it.

**Comment by ccomeaux** [comment]
I have they key to make sure the APK matches the previous one to allow for an upgrade instead of a new application install. That said, I've got an RC set to go, I just need to give it a test. Sorry it's taken so long, but over the last year, lots of small things no longer worked.

I will release something from the develop branch soon, but there have been so many changes that I didn't feel comfortable try to hot fix for the login.

**Comment by Kaligula0** [comment]
You can also release a beta if you would like some of us to test the changes ;)

**Comment by ccomeaux** [comment]
Just created a release if you wanted to give it a spin.
https://github.com/ccomeaux/boardgamegeek4android/releases/tag/6.8.1

**Comment by cmadamsgit** [comment]
Thanks, that's got my new phone logged in!

**Comment by tvedeane** [comment]
Also works on my device!

**Comment by Kaligula0** [comment]
Works on Xperia XZ1C Android 9, too! ♥
