### ISSUE TITLE
Unsuccessful post 307

### ISSUE THREAD

**Issue by justmarks** [ccomeaux/boardgamegeek4android#174]
I tried adding a game to my.collecrion and also recording a play.  in both cases I got a notification for unsuccessful post 307.  when I dismiss it, it immediately comes back.  I tried to clear local cache.  I did a resync.  I uninstalled and reinstalled the latest version.  nothing seems to be able to fix the problem. 

![Screenshot_20220129-081856](https://user-images.githubusercontent.com/1444229/151668591-d02dd890-e0a3-4104-8861-377ce85b2364.png)
![Screenshot_20220129-081841](https://user-images.githubusercontent.com/1444229/151668594-5a1789ee-8e2e-40a8-8a72-35a8ce81945d.png)

**Comment by TulioBarros** [comment]
Please check out these issues. The code is already fixed. But there isn't a new built yet.

https://github.com/ccomeaux/boardgamegeek4android/issues/169
https://github.com/ccomeaux/boardgamegeek4android/issues/172

**Comment by GaddielTundor** [comment]
> I tried adding a game to my.collecrion and also recording a play. in both cases I got a notification for unsuccessful post 307. when I dismiss it, it immediately comes back. I tried to clear local cache. I did a resync. I uninstalled and reinstalled the latest version. nothing seems to be able to fix the problem.
> 
> ![Screenshot_20220129-081856](https://user-images.githubusercontent.com/1444229/151668591-d02dd890-e0a3-4104-8861-377ce85b2364.png) ![Screenshot_20220129-081841](https://user-images.githubusercontent.com/1444229/151668594-5a1789ee-8e2e-40a8-8a72-35a8ce81945d.png)

Exact same issue for me.  I've also tried all the solutions mentioned.

**Comment by corkysru** [comment]
There Haven't been any solutions for this. At least not built ones. I think
the code is fixed but to my knowledge there has not been a release yet with
it implemented.

**Comment by goldeneyeonline** [comment]
It's fixed in the code but not built yet... Please close this issue

**Comment by justmarks** [comment]
Waiting on new build
