### ISSUE TITLE
Can not upload new game to collection- unsuccessfull post 307

### ISSUE THREAD

**Issue by Markosyan-AR** [ccomeaux/boardgamegeek4android#175]
I'm trying to add new game to my collection. It is appears on the screen but can't be synchronized.
Failed with error "Unsuccessful post: 307"

Tried to resync entire data- doesn't help.

**Comment by tvedeane** [comment]
Duplicates #169.

**Comment by Markosyan-AR** [comment]
> Duplicates #169.

ok got it. Is there any plans to make new release? @tvedeane

**Comment by tvedeane** [comment]
> ok got it. Is there any plans to make new release? @tvedeane

That's good question. As far as I know we need to wait for @ccomeaux to trigger new release.

**Comment by tvedeane** [comment]
Here it goes @Markosyan-AR : https://github.com/ccomeaux/boardgamegeek4android/releases/tag/6.8.2.
