### ISSUE TITLE
Lost pending plays

### ISSUE THREAD

**Issue by ludensi** [ccomeaux/boardgamegeek4android#185]
I had a lot of pending plays, there was no sync. with the BGG-homepage. Unfortunately I deinstalled the app with the hope, that I can recover the pending games. Is there any backup-file with the pending plays, that can be recovered by rooting the device (Samsung S8)?

**Comment by ludensi** [comment]
...no answer...

**Comment by ccomeaux** [comment]
Sorry for my lack of response. I think when you uninstall the application the database file is removed as well. It used to back the database up to the cloud, but I think that got removed for a variety of reasons. I would attempt to reinstall to see if those came back.
