### ISSUE TITLE
Unable to change date of play

### ISSUE THREAD

**Issue by marekjeszka** [ccomeaux/boardgamegeek4android#48]
On Samsung Galaxy S IV Mini (Android 4.4.2) I am unable to modify date of an already logged play.
Replication is quite obvious:
- open Plays -> selecy any logged play -> press edit button -> press date -> nothing happens

This works without problems on Nexus 9 (Android 5.0.1).

**Comment by ccomeaux** [comment]
Which version of the application are you seeing this?

**Comment by marekjeszka** [comment]
I have this issue in all versions of 5.0 (in current one and also in 'beta' versions).

**Comment by ccomeaux** [comment]
Not sure what's going on here, but I changed the way it was wired up.

**Comment by henkverleye** [comment]
Updated the app yesterday and have the same issue: not able to select the date of the play, it seems to be fixed to the date of today.
Android 4.2.2, reproduced on smartphone and tablet.

**Comment by ccomeaux** [comment]
Should be fixed in version 5.0.1.
