### ISSUE TITLE
Creating // Editing a user's 'Name' does not trim off trailing spaces

### ISSUE THREAD

**Issue by pvince** [ccomeaux/boardgamegeek4android#49]
I noticed in my "Players" I have the same user apparently showing up twice:
"John Smith"
"John Smith "

Apparently my keyboard has added a " " character after I finish typing a number of times and this has led me to have two different entries.  Trimming off trailing & leading whitespace before saving the user's name could resolve this issue.

I can manually fix the issue by editing the player and removing the trailing whitespace, but it would be nice if when I entered the names it auto-trimmed whitespace.

**Comment by ccomeaux** [comment]
All fields while logging plays and players are trimmed. You could have added the space through the website or an older version of the app. I will update the renaming form to trim as well.

**Comment by ccomeaux** [comment]
Fixed back in 5.1
