### ISSUE TITLE
More statistics

### ISSUE THREAD

**Issue by dkniffin** [ccomeaux/boardgamegeek4android#52]
It'd be nice to see numbers on how many times a given player has won overall, and how many times they've won a certain game.

**Comment by dkniffin** [comment]
As well as who has won a game the most

**Comment by dkniffin** [comment]
It looks like some of this was added per this trello card: https://trello.com/c/u84VH1qk The last activity on there was Sept 3, but it looks like it hasn't been released. Any word on when that will be released?

**Comment by dkniffin** [comment]
@ccomeaux any world on when the next version will be released?

**Comment by ccomeaux** [comment]
I'm really close to something releasable now. I will be working on the last feature this weekend and plan on putting out a new beta next week (fingers crossed!).

**Comment by dkniffin** [comment]
Awesome! How do I get on the list to receive the beta?

**Comment by ccomeaux** [comment]
My estimation skills continue to be terrible. I'm still working toward a release soon, but it won't be this week. When a beta is available, I'll post about it here: https://plus.google.com/communities/109617005048169697217

**Comment by ccomeaux** [comment]
Added in 5.2.
