### ISSUE TITLE
Collection Management

### ISSUE THREAD

**Issue by dkniffin** [ccomeaux/boardgamegeek4android#54]
It'd be nice to have the ability to:
- Add games to collection
- Remove games from collection
- ~~Filter collection by type (eg, so it doesn't show expansions)~~

**Comment by ccomeaux** [comment]
You should already be about to filter collection by 'subtype' - base games, expansions, and accessories.

**Comment by dkniffin** [comment]
Oh, yep.

**Comment by ccomeaux** [comment]
Available in 6.0
