### ISSUE TITLE
app crashes with settings menu

### ISSUE THREAD

**Issue by henkverleye** [ccomeaux/boardgamegeek4android#55]
After updating today, when going to menu item "Settings..." the app stops.
This happened on both tablet and phone.  Both are running Android 4.2.2

**Comment by oddityoverseer13** [comment]
It doesn't crash on mine.

Details:
App version: 5.1
Android version: 5.0
Device: Samsung Galaxy Note 2

**Comment by ccomeaux** [comment]
Fixed in 5.1.1
