### ISSUE TITLE
Request - Ability to view manuals

### ISSUE THREAD

**Issue by Kickbut101** [ccomeaux/boardgamegeek4android#57]
It would be a nice feature to be able to view the list of manuals/rulebooks that are normally on the game page on boardgamegeek.

**Comment by ccomeaux** [comment]
Sorry, but there's no easy way to separate the rulebook from the rest of the files associated with the game. Nor is there an easy way to get the list of the files in the first place. I won't be able to add this feature unless/until a change by BGG.
