### ISSUE TITLE
RetrofitError when updating score

### ISSUE THREAD

**Issue by syllant** [ccomeaux/boardgamegeek4android#59]
Hi,

Each time I update the score in the "Own" section, I get a RetrofitError notification.

However the score is correctly updated on BGG and notification will stop being displayed if I cancel the sync for the related game, so the issue is minor when you are aware of that (I used to clear/re-sync my collection the first times!).

Bgg4Android version: 5.2.3 (not sure about other useful details)

Regards

Sylvain

**Comment by ccomeaux** [comment]
I've received other reports of this. Does the error notification contain any more detail other than "RetrofitError"?

**Comment by syllant** [comment]
No, only this message. I thought you might have more information with your crash reporting service.

With the last update (5.2.5), I also get other synchronization errors, but I should create another issue the next time I'll encounter them.

I'd be happy to provide more help if I can, or to try any debug version with additional diagnostic.

**Comment by icesphere** [comment]
I'm also seeing the retrofit error. I'm on version 5.2.6. It seemed like it started happening after I put in a rating for a game.

**Comment by ccomeaux** [comment]
Fixed in v5.2.7
