### ISSUE TITLE
Sync keeps failing

### ISSUE THREAD

**Issue by chiselwright** [ccomeaux/boardgamegeek4android#60]
For the day or so I've been having trouble with the app failing to sync from the bgg site.

The notification has the error "Sync Error: timeout"

I've tried on different Wi-Fi networks as well as using 4G.
The result is the same.

Any idea what's happening?

**Comment by ccomeaux** [comment]
The BoardGameGeek website is experiencing some trouble, including the entire API being unreachable. Unfortunately, there isn't anything we can do.
