### ISSUE TITLE
Sync Error: Unexpected status line

### ISSUE THREAD

**Issue by chiselwright** [ccomeaux/boardgamegeek4android#61]
I've just updated to the "Sync logic" release and it looks like the status page is (unexpectedly?) returning html instead of json or xml.

![screenshot_20160427-055112 01](https://cloud.githubusercontent.com/assets/85526/14842204/e8c9ee6a-0c3c-11e6-9084-85b3c0ef5a19.png)

**Comment by ccomeaux** [comment]
BGG was down last night for maintenance. I will make the message better, but it should be gone now.
