### ISSUE TITLE
Invalid item.  Play not saved.

### ISSUE THREAD

**Issue by IdahoEv** [ccomeaux/boardgamegeek4android#62]
Several times per day, my phone gets a notification saying "Invalid item. Play not saved." :-(   Sync is otherwise working, and new plays are uploading.

I would guess that this means I have a single bad play record on my phone that can't sync up, but I don't know how to track down which one it is.  I've searched through the code for that string to see if I could work it out, but haven't found the error message.  Any suggestions?

Great app, by the way.  I use it every day and it is a huge service to the BGG community.

**Comment by ccomeaux** [comment]
That is weird. I think that message must be coming from the website, not the code. Can you click the filter button while viewing the list of plays and view only those pending upload or edits and drafts. The problematic play may appear in the list to help me narrow down the problem.

**Comment by IdahoEv** [comment]
@ccomeaux Well, that suggestion solved it for me.  I hadn't noticed that option before.

When I did filter by pending uploads, there was just one:  it was "December 31, 1969.  0 Plays" with no name for the game.   Deleting it caused to the problem to go away.

No idea how I managed to enter that play, but the problem is gone now.  Thanks!

**Comment by IdahoEv** [comment]
The play in question, in case it's helpful.

![screenshot_20160716-205712](https://cloud.githubusercontent.com/assets/440321/16962649/61ebffa8-4da7-11e6-9755-0996dc44afea.png)

**Comment by ccomeaux** [comment]
Weird. It looks like a play without a game, date, or quantity. I'm not sure how that happened either!
