### ISSUE TITLE
Doesn't compile, missing file?

### ISSUE THREAD

**Issue by erwan** [ccomeaux/boardgamegeek4android#63]
I'm trying to compile the app but apparently this class is missing:

`com.boardgamegeek.events.BggEventBusIndex`

Maybe you forgot to add the file to git?

**Comment by ccomeaux** [comment]
This is a file generated by GreenRobot EventBus 3 (see http://greenrobot.org/eventbus/documentation/subscriber-index/). Often this is a symptom of a different compilation problem. Sometimes it can be solved just by compiling again. Please let me know if you continue to experience this and I might be able to help you fix it.

**Comment by erwan** [comment]
Yes indeed, recompilation worked. Thank you!
