### ISSUE TITLE
Error on update player

### ISSUE THREAD

**Issue by Cussa** [ccomeaux/boardgamegeek4android#65]
I'm trying to update my nickname, but the system is getting a error.  Here is a print from the error (with debug value activated).
Username at boardgamegeek: Cussa
![photo384580344326761449](https://cloud.githubusercontent.com/assets/912710/19279700/da02d568-8fb8-11e6-8b10-8ba81db68527.jpg)

**Comment by marekjeszka** [comment]
Hi Cussa. Is this error still visible for you? I've just tried to reproduce it and there is no error visible for me.

**Comment by ccomeaux** [comment]
No longer able to reproduce
