### ISSUE TITLE
Older versions request

### ISSUE THREAD

**Issue by stairway2heaven** [ccomeaux/boardgamegeek4android#69]
Hi there,

The project has been used as part of an experiment previously for an IEEE paper. We are currently trying to recreate the experiment but would require the older versions(2.3 onwards) to do so. Is there any possibility to get access to the older versions? Any help would be much appreciated.

Kind regards,

Joel

**Comment by ccomeaux** [comment]
Does this page have what you are looking for?
https://github.com/ccomeaux/boardgamegeek4android/releases

**Comment by stairway2heaven** [comment]
Hi,

Unfortunately that pages does not have the following releases Jul'10 (2.3), Aug'10 (2.4), Apr'11 (3.0rc), Jun'11 (3.2), Sep (3.3), Oct (3.4) which was used in the IEEE paper.

**Comment by nibuen** [comment]
@stairway2heaven You could try and grab from the commit sha and build yourself: https://github.com/ccomeaux/boardgamegeek4android/commits/develop and just look for it by date since you seem to know that pretty close to when you need it.

**Comment by ccomeaux** [comment]
I won't be adding any releases earlier than are already available here.
