### ISSUE TITLE
Color picker for custom colors

### ISSUE THREAD

**Issue by dkniffin** [ccomeaux/boardgamegeek4android#72]
If you enter something like "blue", it picks the right color to go with it, but if you enter a custom color like "Indigo", it doesn't assign a color. I'd like the ability to pick the color from a color wheel.

**Comment by Vinne2** [comment]
But the meeples are usually in a few common colors, like Red, Blue, Yellow, Green, Black, Pink, White… ;-D

**Comment by dkniffin** [comment]
Yeah, you're right. I'm not sure what I was thinking of when I first opened this. I'll close it.
