### ISSUE TITLE
Out of date links in Google Play store

### ISSUE THREAD

**Issue by mavit** [ccomeaux/boardgamegeek4android#74]
- The description text at https://play.google.com/store/apps/details?id=com.boardgamegeek links to http://code.google.com/p/boardgamegeek, but Google Code was discontinued.
- The developer website link on the same page goes to https://ccomeaux.github.io/boardgamegeek4android/, but this shows a default holding page.

These things make it seem like this app may moribund, but that's not the case.  A better link destination would probably be https://github.com/ccomeaux/boardgamegeek4android.

**Comment by ccomeaux** [comment]
Thanks for the heads up - this is fixed now.
