### ISSUE TITLE
Nickels in PlayStats should be 5 or greater, not 6 or greater

### ISSUE THREAD

**Issue by deisenhut** [ccomeaux/boardgamegeek4android#75]
The "Play Stats" page does not appear to calculate the Nickels correctly. A nickel would be games you have played at least 5 of. But instead it only includes games you have played at least 6 of.

See more information and screenshots, see Facebook post on BoardGameGeek group: https://www.facebook.com/groups/132851767828/permalink/10155024485467829

I downloaded the source code and found the issue.  In ui/model/PlayStats.java:71-73, it reads:

```
} else if (playCount > 5) {
	numberOfNickels++;
}
```

This should be "playCount >= 5" and not just "playCount > 5".   If you are looking for additional contributors for this project, I may be able to help out.

**Comment by ccomeaux** [comment]
I noticed this earlier today and have it fixed locally. I plan on releasing another hot fix in the next day or 2.

**Comment by ccomeaux** [comment]
Fixed in version 6.4
