### ISSUE TITLE
Back buttons (in app and on phone) have different behaviours.

### ISSUE THREAD

**Issue by quasipedia** [ccomeaux/boardgamegeek4android#78]
This is related (but not duplicate) of #76 .

Basically #76 only happens if using the "in app" back button, but not the phone one.
But the same inconsistent behaviour happens in the search section of the app, where the phone back button correctly bring you back from a search result to the search page, while pressing the "in app" back button brings you back to the home page of the app (collection).

**Comment by ccomeaux** [comment]
This is working as designed. What you call the "in app" back button is what Android refers to as the Up button. It is not intended to behaving like the back button. See http://www.techrepublic.com/article/the-android-uis-back-button-vs-up-button-demystified/ for more details.

**Comment by quasipedia** [comment]
Interesting read Chris, it was something I wasn't aware of.

However I still think the two scenarios I presented in this report are both valid cases in which they should indeed behave the same way (as stated in the article you linked, this is a common occurrence).

For search, if you use the play store as an example (as in the article) you will see that the back and up buttons behave identically.

For sort, you can look at the google drive app, and you will notice that the up and back button also behave identically, with the sorting key unaffected.

I changed the phrasing of the issue to reflect the limited scope to search and sorting.
