### ISSUE TITLE
Sync play

### ISSUE THREAD

**Issue by esbenUnipluss** [ccomeaux/boardgamegeek4android#94]
Trying to sync my first two plays (after upgrading to Android 8.0)
Running version 6.6.4

Sync Error
Uploading plays
java.lang.IllegalStateException: Expected
BEGIN_OBJECT but was STRING at line 1 
column 1 path $

I have tried logging in and out again.

**Comment by jasonab** [comment]
I had the same issue in #93, you just need to go to the website and accept their new privacy policy.

**Comment by esbenUnipluss** [comment]
Fixed this by going to BGG.com and accepting the new privacy policy
