### ISSUE TITLE
Error while trying to sync plays

### ISSUE THREAD

**Issue by Cussa** [ccomeaux/boardgamegeek4android#96]
![image](https://user-images.githubusercontent.com/912710/43317432-0a9ac068-919d-11e8-8032-e2112d6b4154.png)

When I try to sync my plays, I'm receiving this error.

**Comment by viovas** [comment]
Same error here. 
Additionally I am getting the following error message:
```
Sync Error
Syncing plays since 2018-04-27
org.simpleframework.xml.core.ValueRequiredExcepion: Unable to satisfy
@org.simpleframework.xml.Attribute(empty=,name=,required=true) on field 'page' private int 
com.boardgamegeek.model.PlayResponse.page
for class
com.boardgamegeek.model.PlayResponse at line 2 
```
Any suggesttions?!

**Comment by ccomeaux** [comment]
BGG's API seems to be replying some unexpected responses.

Someone recently solved the problem with uploading plays by logging a play through the website. After doing triggering a sync, the new play showed up on the phone and all of the plays pending upload went through as well. I haven't had time to figure out why that was the case.

As for the issue with @viovas , that specific error should be resolved in version 6.6.6. But I think that is just hiding the same sort of error @Cussa has.

If either of you are still having issues, you might try logging out and back in.

**Comment by dakkar** [comment]
I was having the same sync problems (weird responses from the server confusing the parser). Logging out & back in, and clearing local data+cache had had no effect. Adding a game to my collection via the website fixed it. Thank you for the app!

**Comment by viovas** [comment]
@ccomeaux The update on version 6.6.6 solved the problem in my case, thanks! :+1:
